all:
	make -C ComplexityInference
	make -C DepGraph
	make -C RangeAnalysis

install:
	make install -C ComplexityInference
	make install -C DepGraph
	make install -C RangeAnalysis

clean:
	make clean -C ComplexityInference
	make clean -C DepGraph
	make clean -C RangeAnalysis

